global:
  namespace: helm-scraper

  image:
    repository: helm-scraper
    tag: "latest"

cronjob:
  schedule: "0 * * * *"
  resources:
    requests:
      memory: "500Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

notion: 
  notionToken: ""
  databaseId: ""
 
argocd:
  enabled: false
  server: ""
  user: ""
  password: ""