apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-cluster-reader
rules:
  - apiGroups: [""]
    resources: ["secrets", "pods", "namespaces"]
    verbs: ["get", "list"]
