apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: helm-scraper
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
              command: ["python", "app.py"]
              envFrom:
                - secretRef:
                    name: helm-scraper-secret
              resources: {{ toYaml .Values.cronjob.resources | nindent 16 }}
          restartPolicy: Never
