apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-cluster-reader-binding
subjects:
  - kind: ServiceAccount
    name: helm-scraper
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: helm-cluster-reader
  apiGroup: rbac.authorization.k8s.io
