apiVersion: v1
kind: Secret
metadata:
  name: helm-scraper-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  NOTION_TOKEN: {{ .Values.secrets.notionToken | b64enc | quote }}
  DATABASE_ID: {{ .Values.secrets.databaseId | b64enc | quote }}