apiVersion: v1
kind: Secret
metadata:
  name: helm-scraper-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  NOTION_TOKEN: {{ .Values.notion.notionToken | b64enc | quote }}
  DATABASE_ID: {{ .Values.notion.databaseId | b64enc | quote }}
  ARGOCD_ENABLED: {{ .Values.argocd.enabled | toString | b64enc | quote }}
  ARGOCD_SERVER: {{ .Values.argocd.server | b64enc | quote }}
  ARGOCD_USERNAME: {{ .Values.argocd.user | b64enc | quote }}
  ARGOCD_PASSWORD: {{ .Values.argocd.password | b64enc | quote }}