name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "helm-scraper/**"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          sudo apt-get install -y apt-transport-https
          echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install -y helm

      - name: Empaquetar el Chart de Helm
        run: helm package helm-scraper

      - name: Actualizar el índice de Helm (`index.yaml`)
        run: helm repo index --url https://lalomiranda.github.io/helm-scraper-chart/ --merge index.yaml .

      - name: Generar `index.html` (si no existe)
        run: |
          if [ ! -f index.html ]; then
            echo '<!DOCTYPE html>' > index.html
            echo '<html lang="es">' >> index.html
            echo '<head><meta charset="UTF-8"><title>Helm Charts Repository</title></head>' >> index.html
            echo '<body><h1>🚀 Helm Charts Repository</h1>' >> index.html
            echo '<p>Última versión publicada:</p>' >> index.html
            VERSION=$(awk '/version:/ { print $2; exit }' index.yaml)
            CHART_NAME=$(awk '/name:/ { print $2; exit }' index.yaml)
            DOWNLOAD_URL=$(awk '/urls:/ { print $2; exit }' index.yaml)
            echo "<p><strong>📦 Chart:</strong> $CHART_NAME</p>" >> index.html
            echo "<p><strong>📌 Versión:</strong> $VERSION</p>" >> index.html
            echo "<p><a href='$DOWNLOAD_URL'>🔗 Descargar Chart</a></p>" >> index.html
            echo '</body></html>' >> index.html
          fi

      - name: Subir cambios (index.yaml & index.html)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git branch --set-upstream-to=origin/main main
          git add index.yaml index.html
          git commit -m "Actualizar Helm Chart y página web" || echo "No changes to commit"
          git push origin main
